name: SuTTS-web

on:
  push:
    branches:
      - master
  workflow_dispatch:
    # manual run
    inputs:
#      hugoVersion:
#        description: "Hugo Version"
#        required: false
#        default: "0.83.0"

# Allow one concurrent deployment
#concurrency:
#  group: "pages"
#  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
#permissions:
permissions: write-all

#permissions:
#  pages: write
#  id-token: write
#  issues: write
#  pull-requests: write
#  contents: write
#  repository-projects: write


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x ]
    steps:

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
      - run: npm run build

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'SuCicada'
          destination-repository-name: 'sutts-homepage'
          user-email: pengyifu@gmail.com
          target-branch: master

      - name: Webhook
        if: always()
        uses: SuCicada/su-action-webhook@latest
        with:
          url: ${{secrets.WEBHOOK_URL}}
          job: ${{toJSON(job)}}
          github: ${{toJSON(github)}}
